server:
  port: 9003

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iainrwolfheart/microservices-config-server
          default-label: main
          clone-on-start: true

